# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-11 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20180411_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='items/%Y/%m/%d')),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('give', 'Give'), ('share', 'Share')], default='Share', max_length=10)),
                ('item', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('data', 'Data'), ('other', 'Other')], default='Data', max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
