# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180429_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publish',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
